# Generated by Django 4.2.3 on 2023-08-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_description_product_descript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descript',
        ),
    ]
