# Generated by Django 4.2.3 on 2023-08-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descript',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
